main = "./src/index.ts"
name = "worker-typescript-template"
compatibility_date = "2023-01-27"
node_compat = true
account_id = "6a18e23bb17ffb10676cd3506b6ea52d"

[vars]
ENVIRONMENT = 'dev'

[env.staging]
name = "typescript-staging"
vars = { ENVIRONMENT = "staging" }
route = "chanon-suttana-pkg.workers.dev/Temp/*"

[env.production]
name = "typescript-api"
vars = { ENVIRONMENT = "production"}
route = "chanon-suttana-pkg.workers.dev/Temp/*"
logpush = true